### ISSUE TITLE
dependency errors on plan / apply

### ISSUE THREAD

**Issue by pjaol** [cn-terraform/terraform-aws-sonarqube#11]
Reopening #10 
Am getting the same error during a plan or apply
What is the dependency order, and can the README be updated to include it?

terraform plan 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/sonar.ecs_fargate/main.tf line 9, in module "ecs-cluster":
   9:   name = "${var.name_prefix}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and one more similar warning elsewhere)

Error: Invalid for_each argument

  on .terraform/modules/sonar.ecs_fargate.ecs-fargate-service/main.tf line 10, in data "aws_lb_target_group" "lb_http_target_groups":
  10:   for_each = var.lb_http_tgs_arns != null ? toset(var.lb_http_tgs_arns) : toset([])

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

Error: Invalid for_each argument

  on .terraform/modules/sonar.ecs_fargate.ecs-fargate-service/main.tf line 20, in data "aws_lb_listener" "lb_http_listeners":
  20:   for_each = var.lb_http_listeners_arns != null ? toset(var.lb_http_listeners_arns) : toset([])

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

Using: 
terraform -version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/random v3.0.0

**Comment by mauro-midolo** [comment]
I received the same error with Terraform 0.13.5

**Comment by jnonino** [comment]
Working on this

**Comment by jnonino** [comment]
Fixed in version [2.0.20](https://registry.terraform.io/modules/cn-terraform/sonarqube/aws/2.0.20).
Please test and reopen if necessary.
Thanks
