### ISSUE TITLE
Tasks continue to start and stop through the ELB

### ISSUE THREAD

**Issue by matty1979** [cn-terraform/terraform-aws-sonarqube#3]
Unable to actually start the service as it's starting and stopping with error 
`STOPPED(Essential container in task exited)`

**Comment by jnonino** [comment]
Hi, I will start working on this. Let you know when it is fixed. Thanks!!

**Comment by jnonino** [comment]
Hi, check on version [2.0.7](https://registry.terraform.io/modules/cn-terraform/sonarqube/aws/2.0.7). The issue is fixed. Let me know if you have any other comments
