### ISSUE TITLE
Default Postgresql variable version (11.7) doesn't work

### ISSUE THREAD

**Issue by fabiodbr** [cn-terraform/terraform-aws-sonarqube#39]
│ Error: error creating RDS cluster: InvalidParameterCombination: Cannot find version 11.7 for aurora-postgresql
│       status code: 400, request id: xxx│ 
│   with module.sonarqube.aws_rds_cluster.aurora_db,
│   on .terraform/modules/sonarqube/database.tf line 29, in resource "aws_rds_cluster" "aurora_db":
│   29: resource "aws_rds_cluster" "aurora_db" {

**Comment by ktibi** [comment]
Need to change to 11.13

**Comment by jnonino** [comment]
Updated to version 14.2 by default
