### ISSUE TITLE
Cannot find version 11.5 for aurora-postgresql

### ISSUE THREAD

**Issue by thinkspill** [cn-terraform/terraform-aws-sonarqube#4]
Full error:

```
Error: error creating RDS cluster: InvalidParameterCombination: Cannot find version 11.5 for aurora-postgresql
```

When I view the Create Database page on the web console, there is an option for aurora-postgresql 11.4 and 11.6, but not 11.5.

<img width="569" alt="aurora-postgresql-versions" src="https://user-images.githubusercontent.com/822133/80559187-97e74200-8991-11ea-8862-ad6ca24be297.png">

**Comment by jnonino** [comment]
Version [2.0.6](https://registry.terraform.io/modules/cn-terraform/sonarqube/aws/2.0.6) is using PostgreSQL 11.6.

I'm working on version 2.0.7 now in case you find another issue or have any comment or suggestion. Thanks!
