### ISSUE TITLE
Error create S3 bucket - BucketAlreadyExists

### ISSUE THREAD

**Issue by guilhermealano** [cn-terraform/terraform-aws-sonarqube#47]
![Captura de Tela_Área de Seleção_20220518115140](https://user-images.githubusercontent.com/98820556/169102269-f981bec3-30f2-4bcb-b736-c11cfc42e572.png)

Hi, I'm trying to run the project, but in the final steps an error occurs when creating the s3 bucket. Would it be possible to change the name of this bucket or pass an argument with another name? I'm attaching a print with the error.

**Comment by guilhermealano** [comment]
![Captura de Tela_Área de Seleção_20220518210727](https://user-images.githubusercontent.com/98820556/169175011-7688cbc3-b96e-4465-a945-bb801ba96dfc.png)

After using the new version, this error occurs.

**Comment by jnonino** [comment]
[2.0.33](https://registry.terraform.io/modules/cn-terraform/sonarqube/aws/2.0.32) should work now. Can you test it?
Thanks and sorry for the inconvenience
