### ISSUE TITLE
Disable loadbalancing logs

### ISSUE THREAD

**Issue by guilhermealano** [cn-terraform/terraform-aws-sonarqube#50]
Is it possible to edit main.tf so that loadbalancing logs are not enabled? It is enabled to save these logs to an S3 bucket.

**Comment by guilhermealano** [comment]
And also that this S3 bucket is not created for LB logs.

**Comment by jnonino** [comment]
Version [2.0.35](https://registry.terraform.io/modules/cn-terraform/sonarqube/aws/2.0.35) contains some variables for that. Please take a look and let me know how it works.

**Comment by guilhermealano** [comment]
It worked, thanks.
