### ISSUE TITLE
Port 9001 make tg-1 unhealthy

### ISSUE THREAD

**Issue by mhmdio** [cn-terraform/terraform-aws-sonarqube#6]
Port 9001 makes tg-1 unhealthy, so the ECS service keep restarting due to the health checks from the LB on port 9001, any idea? for now, I set the health check for that port to override with port 9000

**Comment by jnonino** [comment]
Hi, Try it with version [2.0.13](https://registry.terraform.io/modules/cn-terraform/sonarqube/aws/2.0.13).
Let me know if that works for you!
